app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


userapi:
    type: rest
    resource: "@AppBundle/Resources/config/routing.yml"