
user_all:
    pattern:  api/users
    defaults: { _controller: AppBundle:User:all, _format: json }
    requirements:
        _method: GET

user_get:
    pattern:  api/users/{id}
    defaults: { _controller: AppBundle:User:get, _format: json }
    requirements:
        _method: GET

book_get:
    pattern:  api/book/{id}
    defaults: { _controller: AppBundle:BookAddress:get, _format: json }
    requirements:
        _method: GET
